import math
import random
from typing import Optional, Dict, Tuple

import moderngl as mlg
import numpy

from moderngl_window.geometry import AttributeNames
from moderngl_window.opengl.vao import VAO


def icosphere(
    radius: float = 0.5,
    subdivisions: int = 3,
    randomization: float = 0.0,
    normals: bool = True,
    uvs: bool = True,
    name: Optional[str] = None,
    attr_names: type[AttributeNames] = AttributeNames,
) -> VAO:
    """Creates an icosphere (geodesic polyhedron).
    
    Generated by subdividing a regular icosahedron.

    Keyword Args:
        radius (float): Radius of the sphere
        subdivisions (int): Number of subdivisions (0 is a regular icosahedron)
        normals (bool): Include normals in the VAO
        uvs (bool): Include texture coordinates in the VAO
        name (str): An optional name for the VAO
        attr_names (AttributeNames): Attribute names
    Returns:
        A :py:class:`VAO` instance
    """
    # Golden ratio
    phi = (1.0 + math.sqrt(5.0)) / 2.0

    # Base icosahedron vertices
    vertices = [
        (-1,  phi,  0), ( 1,  phi,  0), (-1, -phi,  0), ( 1, -phi,  0),
        ( 0, -1,  phi), ( 0,  1,  phi), ( 0, -1, -phi), ( 0,  1, -phi),
        ( phi,  0, -1), ( phi,  0,  1), (-phi,  0, -1), (-phi,  0,  1),
    ]
    # Normalize base vertices
    vertices = [(x / math.sqrt(x*x + y*y + z*z), y / math.sqrt(x*x + y*y + z*z), z / math.sqrt(x*x + y*y + z*z)) 
                for x, y, z in vertices]

    # Base icosahedron faces (indices)
    faces = [
        (0, 11, 5), (0, 5, 1), (0, 1, 7), (0, 7, 10), (0, 10, 11),
        (1, 5, 9), (5, 11, 4), (11, 10, 2), (10, 7, 6), (7, 1, 8),
        (3, 9, 4), (3, 4, 2), (3, 2, 6), (3, 6, 8), (3, 8, 9),
        (4, 9, 5), (2, 4, 11), (6, 2, 10), (8, 6, 7), (9, 8, 1)
    ]

    # Subdivision cache for midpoints
    middle_point_cache: Dict[Tuple[int, int], int] = {}

    def get_middle_point(p1: int, p2: int) -> int:
        # Check if we already have the midpoint for this edge
        key = tuple(sorted((p1, p2)))
        if key in middle_point_cache:
            return middle_point_cache[key]
        
        # Calculate midpoint
        v1 = vertices[p1]
        v2 = vertices[p2]
        middle = (
            (v1[0] + v2[0]) / 2,
            (v1[1] + v2[1]) / 2,
            (v1[2] + v2[2]) / 2
        )
        
        # Project to sphere
        length = math.sqrt(middle[0]**2 + middle[1]**2 + middle[2]**2)
        middle = (middle[0] / length, middle[1] / length, middle[2] / length)
        
        # Add to vertices and cache
        vertices.append(middle)
        index = len(vertices) - 1
        middle_point_cache[key] = index
        return index

    # Perform subdivisions
    for _ in range(subdivisions):
        faces_new = []
        for tri in faces:
            # Get midpoints
            a = get_middle_point(tri[0], tri[1])
            b = get_middle_point(tri[1], tri[2])
            c = get_middle_point(tri[2], tri[0])
            
            # Create 4 new triangles
            faces_new.append((tri[0], a, c))
            faces_new.append((tri[1], b, a))
            faces_new.append((tri[2], c, b))
            faces_new.append((a, b, c))
        faces = faces_new

    # Final vertex data
    count = len(vertices)
    
    # Randomization for planet-like irregular pattern
    if randomization > 0.0:
        random.seed(42) # Deterministic for same subdivisions
        vertices_randomized = []
        for v in vertices:
            offset = 1.0 + (random.random() * 2.0 - 1.0) * randomization
            vertices_randomized.append((v[0] * offset, v[1] * offset, v[2] * offset))
        vertices = vertices_randomized

    vertices_l = numpy.array(vertices, dtype=numpy.float32) * radius
    
    # Recalculate normals if randomized, otherwise they are just normalized positions
    if normals:
        if randomization > 0.0:
            # For a proper planet we might want face normals or something else, 
            # but usually we want to keep them smooth-ish or recalculate.
            # Here we just keep them smooth pointing out for simplicity in this step.
            normals_l = numpy.array(vertices, dtype=numpy.float32)
            for i in range(len(normals_l)):
                mag = numpy.linalg.norm(normals_l[i])
                normals_l[i] /= mag
        else:
            normals_l = numpy.array(vertices, dtype=numpy.float32)
    
    # Basic spherical UVs
    if uvs:
        uvs_l = numpy.zeros((count, 2), dtype=numpy.float32)
        for i, (x, y, z) in enumerate(vertices):
            # Normalizing just in case, though they should be normalized
            mag = math.sqrt(x*x + y*y + z*z)
            nx, ny, nz = x/mag, y/mag, z/mag
            uvs_l[i, 0] = 0.5 + math.atan2(nz, nx) / (2 * math.pi)
            uvs_l[i, 1] = 0.5 - math.asin(ny) / math.pi

    # Create VAO
    vao = VAO(name or "icosphere", mode=mlg.TRIANGLES)
    vao.buffer(vertices_l, "3f", [attr_names.POSITION])
    
    if normals:
        vao.buffer(normals_l, "3f", [attr_names.NORMAL])
        
    if uvs:
        vao.buffer(uvs_l, "2f", [attr_names.TEXCOORD_0])

    indices = numpy.array(faces, dtype=numpy.uint32).flatten()
    vao.index_buffer(indices, index_element_size=4)

    return vao
